"""
Weekly deal health report — emails a list of deals that were never accepted
by the buyer (bid_responses = 0 across all history).

Two categories:
  1. Never sent     — bid_requests = 0 (trafficking issue)
  2. Never accepted — bid_requests > 0, bid_responses = 0 (buyer hasn't accepted)

Run manually:  python weekly_report.py
Run on a cron: GitHub Actions weekly_report.yml
Test sender:   python weekly_report.py --test
"""

from __future__ import annotations

import argparse
import os
from datetime import date
from pathlib import Path

from agentmail import AgentMail

import pandas as pd
import sqlalchemy


# ── env / config ──────────────────────────────────────────────────────────────

def _load_dotenv() -> None:
    env_file = Path(__file__).parent / ".env"
    if not env_file.exists():
        return
    for line in env_file.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))


AE_NAMES = {
    "AShah": "Amit Shah",
    "BKaretny": "Ben Karetny",
    "BRobinson": "Brian Robinson",
    "DDivack": "Dana Divack",
    "DVarvaro": "Danielle Varvaro",
    "ILee": "Ivy Lee",
    "Ivy": "Ivy Lee",
    "JAmalfi": "Julie Amalfi",
    "JGentile": "Jeremy Gentile",
    "KWebb": "House",
    "RShore": "Rob Shore",
    "SCarroll": "Summer Carroll",
    "THern": "Theresa Hern",
    "House": "House",
}


# ── data ──────────────────────────────────────────────────────────────────────

def load_never_accepted() -> tuple[pd.DataFrame, pd.DataFrame]:
    engine = sqlalchemy.create_engine(os.environ["DATABASE_URL"])
    with engine.connect() as conn:
        df = pd.read_sql(
            """
            SELECT
                deal,
                SUM(bid_requests)  AS total_bid_requests,
                SUM(bid_responses) AS total_bid_responses,
                COUNT(DISTINCT date) AS days_in_data,
                MIN(date) AS first_seen
            FROM magnite_deal_daily
            WHERE deal IS NOT NULL
              AND deal != ''
              AND UPPER(TRIM(REPLACE(deal, '-', ''))) != 'NA'
            GROUP BY deal
            HAVING SUM(bid_responses) = 0
            ORDER BY days_in_data DESC
            """,
            conn,
        )

    df["seller"] = (
        df["deal"]
        .str.extract(r"Team-(?:USA|INTL)_([A-Za-z]+)", expand=False)
        .map(AE_NAMES)
        .fillna("Unknown")
    )

    never_sent     = df[df["total_bid_requests"] == 0].copy()
    never_accepted = df[df["total_bid_requests"]  > 0].copy()

    return never_sent, never_accepted


# ── email ─────────────────────────────────────────────────────────────────────

def _table_html(df: pd.DataFrame, columns: list[str], headers: list[str]) -> str:
    rows_html = ""
    for _, row in df[columns].iterrows():
        cells = "".join(f"<td style='padding:6px 12px;border-bottom:1px solid #eee'>{row[c]}</td>" for c in columns)
        rows_html += f"<tr>{cells}</tr>"

    header_html = "".join(
        f"<th style='padding:6px 12px;text-align:left;background:#f0f4f8;border-bottom:2px solid #ccc'>{h}</th>"
        for h in headers
    )
    return f"""
    <table style='border-collapse:collapse;width:100%;font-family:Arial,sans-serif;font-size:13px'>
      <thead><tr>{header_html}</tr></thead>
      <tbody>{rows_html}</tbody>
    </table>"""


def build_email(never_sent: pd.DataFrame, never_accepted: pd.DataFrame) -> str:
    today = date.today().strftime("%B %d, %Y")

    def section(title: str, color: str, df: pd.DataFrame, cols: list, headers: list) -> str:
        if df.empty:
            return f"<h3 style='color:{color}'>{title}</h3><p>None — all clear.</p>"
        return f"""
        <h3 style='color:{color}'>{title} ({len(df)} deals)</h3>
        {_table_html(df, cols, headers)}
        <br>"""

    body = f"""
    <html><body style='font-family:Arial,sans-serif;color:#333;max-width:900px;margin:auto;padding:20px'>
      <h2>Weekly Deal Health Report — {today}</h2>
      <p>Deals with <strong>zero impressions and no buyer response</strong> across all historical data.</p>

      {section(
          "🚫 Never sent to buyer — check trafficking",
          "#c0392b",
          never_sent,
          ["deal", "seller", "days_in_data", "first_seen"],
          ["Deal", "Seller", "Days in data", "First seen"],
      )}

      {section(
          "⚠️ Sent but never accepted by buyer",
          "#e67e22",
          never_accepted,
          ["deal", "seller", "total_bid_requests", "days_in_data", "first_seen"],
          ["Deal", "Seller", "Total bid requests", "Days in data", "First seen"],
      )}

      <hr style='margin-top:30px'>
      <p style='font-size:11px;color:#999'>
        Generated by Newsweek × Magnite dashboard &mdash;
        <a href='https://newsweek-magnite.streamlit.app'>View dashboard</a>
      </p>
    </body></html>
    """
    return body


def send_email(html_body: str) -> None:
    client    = AgentMail(api_key=os.environ["AGENTMAIL_API_KEY"])
    inbox_id  = os.environ["AGENTMAIL_INBOX_ID"]
    recipient = os.environ["REPORT_TO_EMAIL"]

    client.inboxes.messages.send(
        inbox_id,
        to=recipient,
        subject=f"Weekly Deal Health Report — {date.today().strftime('%b %d, %Y')}",
        html=html_body,
    )
    print(f"Email sent to {recipient}")


# ── main ──────────────────────────────────────────────────────────────────────

def _sample_data() -> tuple[pd.DataFrame, pd.DataFrame]:
    never_sent = pd.DataFrame([{
        "deal": "Team-USA_RShore-TEST-NEVER-SENT",
        "seller": "Rob Shore",
        "days_in_data": 7,
        "first_seen": "2026-05-11",
        "total_bid_requests": 0,
        "total_bid_responses": 0,
    }])
    never_accepted = pd.DataFrame([{
        "deal": "Team-USA_ILee-TEST-NEVER-ACCEPTED",
        "seller": "Ivy Lee",
        "days_in_data": 14,
        "first_seen": "2026-05-04",
        "total_bid_requests": 4200,
        "total_bid_responses": 0,
    }])
    return never_sent, never_accepted


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--test", action="store_true", help="Send a sample email without hitting the database")
    args = parser.parse_args()

    _load_dotenv()

    if args.test:
        never_sent, never_accepted = _sample_data()
        print("Test mode — skipping database query.")
    else:
        never_sent, never_accepted = load_never_accepted()

    print(f"Never sent: {len(never_sent)} | Never accepted: {len(never_accepted)}")
    html = build_email(never_sent, never_accepted)
    send_email(html)


if __name__ == "__main__":
    main()
